In [ ]:
!pip install snscrape

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
Collecting snscrape
  Downloading snscrape-0.6.2.20230320-py3-none-any.whl (71 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 71.8/71.8 kB 2.0 MB/s eta 0:00:00
Requirement already satisfied: lxml in /usr/local/lib/python3.10/dist-packages (from snscrape) (4.9.2)
Requirement already satisfied: beautifulsoup4 in /usr/local/lib/python3.10/dist-packages (from snscrape) (4.11.2)
Requirement already satisfied: requests[socks] in /usr/local/lib/python3.10/dist-packages (from snscrape) (2.27.1)
Requirement already satisfied: filelock in /usr/local/lib/python3.10/dist-packages (from snscrape) (3.12.0)
Requirement already satisfied: soupsieve>1.2 in /usr/local/lib/python3.10/dist-packages (from beautifulsoup4->snscrape) (2.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->snscrape) (3.4)
Requirement already satisfied: charset-normalizer~=2.0.0 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->snscrape) (2.0.12)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->snscrape) (1.26.15)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->snscrape) (2022.12.7)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6 in /usr/local/lib/python3.10/dist-packages (from requests[socks]->snscrape) (1.7.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.6.2.20230320

In [ ]:
import pandas as pd
import snscrape.modules.twitter as sntwit

In [ ]:
max_tweet = 50
tweet_list = []
for t, tweet in enumerate(sntwit.TwitterSearchScraper('from : elonmusk').get_items()):
 if t > max_tweet:
      break
 else:
          tweet_list.append([tweet.date, tweet.id, tweet.content,tweet.user.username,tweet.hashtags,tweet.cashtags])

<ipython-input-83-ef7095e6eeeb>:7: DeprecatedFeatureWarning: content is deprecated, use rawContent instead
  tweet_list.append([tweet.date, tweet.id, tweet.content,tweet.user.username,tweet.hashtags,tweet.cashtags])

In [ ]:
tweet_list[2]

[datetime.datetime(2023, 4, 18, 23, 56, 45, tzinfo=datetime.timezone.utc),
 1648475685965672452,
 '@elonmusk @TheRabbitHole84 The hyper capitalist world you live in keeps people away from having kids',
 'FiggyDaniel',
 None,
 None]

In [ ]:
elonmusk_df = pd.DataFrame(tweet_list, columns = ["tarih", "tweet ID", "içerik", "kullanıcı","hashtags","cashtags"])
elonmusk_df.head(10)

,tarih,tweet ID,içerik,kullanıcı,hashtags,cashtags
0,2023-04-18 23:57:07+00:00,1648475779083423744,@elonmusk\n@glennkirschner2\n@JillWineBanks\n@...,OaktreeVictor,None,None
1,2023-04-18 23:56:56+00:00,1648475731834572801,@OliLondonTV @elonmusk I've been booted from T...,VesFreedom,None,None
2,2023-04-18 23:56:45+00:00,1648475685965672452,@elonmusk @TheRabbitHole84 The hyper capitalis...,FiggyDaniel,None,None
3,2023-04-18 23:56:43+00:00,1648475678139092992,@elonmusk Man I love you. Just in case no one ...,JoelChitty,None,None
4,2023-04-18 23:56:42+00:00,1648475671822495745,"Dear @elonmusk, can you take away the option o...",jehlimus,None,None
5,2023-04-18 23:56:33+00:00,1648475637861208070,"Elon Musk New TWITTER Logo Design ""Musk It Twi...",f9art,None,None
6,2023-04-18 23:56:28+00:00,1648475616860340224,@elonmusk Why hasn't Fox News been labeled? I'...,joshsallon,None,None
7,2023-04-18 23:55:54+00:00,1648475472588849156,@FreedomFight75 @IzMogUgla @Lanampayne @Pierre...,TimFitzMaguire,None,None
8,2023-04-18 23:55:43+00:00,1648475425830756352,@CalmDownHabiby @TheAdvocateMag @glaad @elonmu...,gaytravelguides,None,None
9,2023-04-18 23:55:40+00:00,1648475413344292865,@elonmusk @KanekoaTheGreat @joshrogin @glennbe...,tfa8889,None,None

In [ ]:
elonmusk_df.tail(10)

,tarih,tweet ID,içerik,kullanıcı,hashtags,cashtags
41,2023-04-18 23:50:48+00:00,1648474188771106819,"@elonmusk @Lukewearechange To be clear, that v...",Tyler_Pond_,None,None
42,2023-04-18 23:50:03+00:00,1648473998832041984,@POTUS @elonmusk @NASA \nTo avoid massive coro...,SookeGill,None,None
43,2023-04-18 23:49:36+00:00,1648473886340837379,@starkrob21 @elonmusk @TheGeneral_0 @MagaCupca...,GusBennett8,None,None
44,2023-04-18 23:49:11+00:00,1648473784016568321,"@elonmusk @Lukewearechange It's from 2020, put...",RamenTumbleweed,None,None
45,2023-04-18 23:48:46+00:00,1648473676705337346,@krassenstein I don’t think @elonmusk followin...,goostrey,None,None
46,2023-04-18 23:48:18+00:00,1648473558790864897,@elonmusk Thank you from canaduh,Filthy_Casual1,None,None
47,2023-04-18 23:48:09+00:00,1648473521897758720,@elonmusk X Corp? Like from X-Men?,meQyuri,None,None
48,2023-04-18 23:47:52+00:00,1648473449852198914,"@elonmusk @JonErlichman Yes, bring on resonant...",learnwithduncan,None,None
49,2023-04-18 23:47:51+00:00,1648473447163629569,"Thank you @elonmusk. Actually, you might need ...",freecitizen085,None,None
50,2023-04-18 23:47:05+00:00,1648473253076430849,@elonmusk we need a better system of voting. O...,Alexthehumble1,None,None

In [ ]:
elonmusk_df.to_csv(r"C:\Users\Lenovo\OneDrive\Masaüstü\twitter\elonmusk.csv", sep = ",", encoding = "utf-8-sig")

In [ ]:
elonmusk_list = []
for t, tweet in enumerate(sntwit.TwitterSearchScraper('#elonmusk since:2022-06-01 until:2022-06-02').get_items()):
 if t > 20:
   break
 else:
     elonmusk_list.append([tweet.date, tweet.id, tweet.content,tweet.user.username,tweet.hashtags,tweet.cashtags])

<ipython-input-99-151de91d9547>:6: DeprecatedFeatureWarning: content is deprecated, use rawContent instead
  elonmusk_list.append([tweet.date, tweet.id, tweet.content,tweet.user.username,tweet.hashtags,tweet.cashtags])

In [ ]:
elonmusk_list[5]

[datetime.datetime(2022, 6, 1, 23, 45, 12, tzinfo=datetime.timezone.utc),
 1532146275021467648,
 'I was almost killed by a truck | Elon Musk https://t.co/rW10e5ByBl via @YouTube \n\nWhy Tesla will not make motorcycles. #ElonMusk #Tesla',
 'LaciMarieKnight',
 ['ElonMusk', 'Tesla'],
 None]

In [ ]:
elonmusk_df = pd.DataFrame(elonmusk_list, columns = ["tarih", "tweet ID", "içerik", "kullanıcı","hashtags","cashtags"])
elonmusk_df.head(10)

,tarih,tweet ID,içerik,kullanıcı,hashtags,cashtags
0,2022-06-01 23:58:10+00:00,1532149537531633664,#ElonMusk Takes Dig at #DeutscheBank ’s ‘Green...,epochtimestoday,"[ElonMusk, DeutscheBank, Tesla]",None
1,2022-06-01 23:57:14+00:00,1532149301618610176,#Internacional Elon Musk lanza ultimátum a emp...,elmercuriotam,"[Internacional, ElonMusk, Tesla, ultimatum, Cd...",None
2,2022-06-01 23:56:20+00:00,1532149077173063680,@AmandaLarreni I disagree when #ElonMusk says ...,ImpeachTheAll,[ElonMusk],None
3,2022-06-01 23:45:45+00:00,1532146413026557953,テスラがアップルAirPlay対応を検討。車載オーディオの音質改善に向け（PHILE WEB...,elonmuskrati,"[elonmusk, イーロンマスク]",None
4,2022-06-01 23:45:44+00:00,1532146408006066176,イーロン・マスク氏「EV販売を許可されない限り、テスラはインドに工場を設置しない」 (202...,elonmuskrati,"[elonmusk, イーロンマスク]",None
5,2022-06-01 23:45:12+00:00,1532146275021467648,I was almost killed by a truck | Elon Musk htt...,LaciMarieKnight,"[ElonMusk, Tesla]",None
6,2022-06-01 23:44:52+00:00,1532146191571591168,@elonmusk What the hell man! Pick up your cell...,ALPHAUS_,"[thealpha, ElonMusk, ALPHA]",None
7,2022-06-01 23:43:03+00:00,1532145731909439488,Check out my NFT listing on OpenSea!\n\n1. Fol...,Tayyabtahi9,"[NFTCommunity, NFTs, NFTdrop, Whitelist, white...",None
8,2022-06-01 23:42:54+00:00,1532145697373536257,@MrSlowPlay @RRahopara @InvestIngClues @elonmu...,AustinLuongo4,[elonmusk],[RDBX]
9,2022-06-01 23:41:34+00:00,1532145361116184576,#ElonMusk #ForPresident,Leonardovyv,"[ElonMusk, ForPresident]",None